version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loanbot-api
    env_file:
      - .env
    environment:
      - ENV=${ENV:-local}
      - PORT=${PORT:-8000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOANBOT_ALLOWED_ORIGINS=${LOANBOT_ALLOWED_ORIGINS:-*}
      - DATA_GO_KR_KEY=${DATA_GO_KR_KEY:-}
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./:/app
    command: >-
      uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      vectorstore:
        condition: service_started

  vectorstore:
    image: chromadb/chroma:latest
    container_name: loanbot-vectorstore
    env_file:
      - .env
    volumes:
      - ./data/embeddings:/data
    ports:
      - "8001:8000"
    restart: unless-stopped
